spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://127.0.0.1:5432/forest'
    username: 'forest'
    password: 'forest'
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
mybatis:
  mapper-locations: classpath:com/example/demo/**/mapper/*.xml
  type-aliases-package: com.example.demo
server:
  port: 80
logging: # logging
  level:
    root: info
    com:
      example: debug
    org:
      apache:
        http:
          wire: debug
        tomcat:
          util:
            http: info
